### PR TITLE
Wip visu params

### PR DESCRIPTION
**Pull request by TanDro**
Add possibility to use module parameters in visualization.

### CODE REVIEW

**Comment by cklb** [comment]
Could you rebase onto the current develop please?

**Comment by cklb** [comment]
Since I was implementing a drop-down menu for the visualizers anyway, I added a setter method for the config in 54523b690ceb010bee9f2fac4bef59ba51626fcb. Does that work for you?

**Comment by TanDro** [comment]
I have tested 54523b6 and it is exactly what we want. I close this pull request. Cherry-pick this into the develop yourself or should I put another pull request?

**Comment by cklb** [comment]
Alright. I'm going to merge the other one, then.

**Pull request closed without merging**
