### PR TITLE
Added very basic matplotlib animation interface

### PR DESCRIPTION
**Pull request by riemarc**
[mr_conda_list_20160515.txt](https://github.com/cklb/pymoskito/files/265019/mr_conda_list_20160515.txt)

### CODE REVIEW

**Comment by riemarc** [comment]
Here is the minimal conda environment:
[mr_conda_env_20160515_2.txt](https://github.com/cklb/pymoskito/files/265084/mr_conda_env_20160515_2.txt)
Consider to add pypango to the requirements.txt.
Without pango i get:
`symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenType`

**Comment by cklb** [comment]
I like the idea of providing an alternative interface for visualization as this would also solve the problem considered in #4. I will try to merge it in the next few days.

Greets Stefan

**Comment by cklb** [comment]
merged into develop branch

**Comment by riemarc** [comment]
Now
`import PyQt5.QtCore`
`import pyqtgraph`
throws
`RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class`

Any suggestions?

**Comment by cklb** [comment]
This error is caused by pyqtgraph which imports PyQt4. 
The current develop branch of pyqtgraph has PyQt5 support but it will prefer to import PyQt4 if it is found in sys.path. For now simply uninstalling PyQt4  and using the pyqtgraph development version solves the problem. 
This problem will hopefully be resolved soon.

**Pull request closed without merging**
