### PR TITLE
Datenhandling verschiedener Regimes

### PR DESCRIPTION
**Pull request by TanDro**
Die nach der Simulation erzeigten Daten werden dem jeweiligen Regime dict hinzugefügt, Anpassung der sanity checks notwendig gewesen. getattr liefert bei nicht vorhandenen Attribut eine Exception und nicht None zurück. @cklb wie findest du diese Lösung?

### CODE REVIEW

**Comment by cklb** [comment]
Thanks for pointing out the issue concerning malformed module names, the default parameter of `getattr` was missing. I've added a fix for this issue in the develop branch.

For the storage, as `data` itself is a dictionary, holding the simulation settings as well as the results, I do not really see the point why they should be stored in a dictionary that already holds the settings.
Basically it is not even sure that any of the simulated settings actually fits the one provided by the regime which is currently selected. (Line 812)

It may be wiser to offer a functionlity to read an result file (*.pmr) and apply the settings stored in there to the current property list.

**Comment by TanDro** [comment]
I included the communicated tasks. 

FYI: On my pc I got the following errors by running the tests with python 3.7:

`test_setData (pymoskito.tests.test_simulation_interface.TestPropertyItem) ... 24/09/2018 23:01:19 - PropertyItem - ERROR - unexpected EOF while parsing (<unknown>, line 1)`
`Traceback (most recent call last):`
`  File "/Users/murdoc/Documents/development/git/pymoskito/pymoskito/simulation_interface.py", line 56, in setData`
`    self._data = ast.literal_eval(Any)`
`  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 46, in literal_eval`
`    node_or_string = parse(node_or_string, mode='eval')`
`  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 35, in parse`
`    return compile(source, filename, mode, PyCF_ONLY_AST)`
`  File "<unknown>", line 1`
`    [1, 2`
`        ^`
`SyntaxError: unexpected EOF while parsing`
`ok`

and 
`test_generic_calls (pymoskito.tests.test_registry.TestGetterCalls) ... FAIL`
`test_special_call (pymoskito.tests.test_registry.TestGetterCalls) ... FAIL`
`test_string_call (pymoskito.tests.test_registry.TestGetterCalls) ... FAIL`

**Comment by cklb** [comment]
> I included the communicated tasks.
> 
> FYI: On my pc I got the following errors by running the tests with python 3.7:
> 
> `test_setData (pymoskito.tests.test_simulation_interface.TestPropertyItem) ... 24/09/2018 23:01:19 - PropertyItem - ERROR - unexpected EOF while parsing (<unknown>, line 1)`
> `Traceback (most recent call last):`
> `File "/Users/murdoc/Documents/development/git/pymoskito/pymoskito/simulation_interface.py", line 56, in setData`
> `self._data = ast.literal_eval(Any)`
> `File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 46, in literal_eval`
> `node_or_string = parse(node_or_string, mode='eval')`
> `File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 35, in parse`
> `return compile(source, filename, mode, PyCF_ONLY_AST)`
> `File "<unknown>", line 1`
> `[1, 2`
> `^`
> `SyntaxError: unexpected EOF while parsing`
> `ok`

As the last line shows, this one is not really an error but the successful test of the error detection

> `test_generic_calls (pymoskito.tests.test_registry.TestGetterCalls) ... FAIL`
> `test_special_call (pymoskito.tests.test_registry.TestGetterCalls) ... FAIL`
> `test_string_call (pymoskito.tests.test_registry.TestGetterCalls) ... FAIL`

These three never failed before and are currently working on my machine, would you mind posting their stacktrace? Furthermore, `test_visualizer_call` does not fail?

**Comment by cklb** [comment]
Nice feature, unfortunately there is a little drawback: If you activate the feature and open a new plot window, the plot will start to automatically resize if you move the cursor the the boundaries of the plot window which makes reading the values quite complicated.
Furthermore, the flag should be handled in the `view` menu and stored in the configuration file to remember the setting (see e.g. the default save path)

**Comment by TanDro** [comment]
> > I included the communicated tasks.
> > FYI: On my pc I got the following errors by running the tests with python 3.7:
> > `test_setData (pymoskito.tests.test_simulation_interface.TestPropertyItem) ... 24/09/2018 23:01:19 - PropertyItem - ERROR - unexpected EOF while parsing (<unknown>, line 1)`
> > `Traceback (most recent call last):`
> > `File "/Users/murdoc/Documents/development/git/pymoskito/pymoskito/simulation_interface.py", line 56, in setData`
> > `self._data = ast.literal_eval(Any)`
> > `File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 46, in literal_eval`
> > `node_or_string = parse(node_or_string, mode='eval')`
> > `File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 35, in parse`
> > `return compile(source, filename, mode, PyCF_ONLY_AST)`
> > `File "<unknown>", line 1`
> > `[1, 2`
> > `^`
> > `SyntaxError: unexpected EOF while parsing`
> > `ok`

You are totally right. I saw the ok too, but was not sure, if the error was expected in this way.

> As the last line shows, this one is not really an error but the successful test of the error detection
> 
> > `test_generic_calls (pymoskito.tests.test_registry.TestGetterCalls) ... FAIL`
> > `test_special_call (pymoskito.tests.test_registry.TestGetterCalls) ... FAIL`
> > `test_string_call (pymoskito.tests.test_registry.TestGetterCalls) ... FAIL`
> 
> These three never failed before and are currently working on my machine, would you mind posting their stacktrace? Furthermore, `test_visualizer_call` does not fail?

With the current commit I don't get these errors again.

**Comment by cklb** [comment]
Since the current state seems sufficient, I'm going to merge this and open a new release branch for the fine tuning.
Please remeber to add the new features to the changelog in the v0.3.0rc1 branch

**Pull request closed without merging**
